version: "3"

services:
  web:
    build: .
    restart: always
    command: start
    env_file:
      - node.env
    ports:
      - "80:80"
  db:
    image: mongo
    restart: always
    env_file:
      - mongo.env
    ports:
      - "27017:27017"
